//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliver.CisteraScreenCaptureService.UserSessionAgent.CisteraScreenCaptureService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CisteraScreenCaptureService.IUserSessionApi")]
    public interface IUserSessionApi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSessionApi/GetSettings", ReplyAction="http://tempuri.org/IUserSessionApi/GetSettingsResponse")]
        Cliver.CisteraScreenCaptureService.Settings.GeneralSettings GetSettings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSessionApi/GetSettings", ReplyAction="http://tempuri.org/IUserSessionApi/GetSettingsResponse")]
        System.Threading.Tasks.Task<Cliver.CisteraScreenCaptureService.Settings.GeneralSettings> GetSettingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSessionApi/SaveSettings", ReplyAction="http://tempuri.org/IUserSessionApi/SaveSettingsResponse")]
        void SaveSettings(Cliver.CisteraScreenCaptureService.Settings.GeneralSettings general);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSessionApi/SaveSettings", ReplyAction="http://tempuri.org/IUserSessionApi/SaveSettingsResponse")]
        System.Threading.Tasks.Task SaveSettingsAsync(Cliver.CisteraScreenCaptureService.Settings.GeneralSettings general);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserSessionApiChannel : Cliver.CisteraScreenCaptureService.UserSessionAgent.CisteraScreenCaptureService.IUserSessionApi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserSessionApiClient : System.ServiceModel.ClientBase<Cliver.CisteraScreenCaptureService.UserSessionAgent.CisteraScreenCaptureService.IUserSessionApi>, Cliver.CisteraScreenCaptureService.UserSessionAgent.CisteraScreenCaptureService.IUserSessionApi {
        
        public UserSessionApiClient() {
        }
        
        public UserSessionApiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserSessionApiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserSessionApiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserSessionApiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cliver.CisteraScreenCaptureService.Settings.GeneralSettings GetSettings() {
            return base.Channel.GetSettings();
        }
        
        public System.Threading.Tasks.Task<Cliver.CisteraScreenCaptureService.Settings.GeneralSettings> GetSettingsAsync() {
            return base.Channel.GetSettingsAsync();
        }
        
        public void SaveSettings(Cliver.CisteraScreenCaptureService.Settings.GeneralSettings general) {
            base.Channel.SaveSettings(general);
        }
        
        public System.Threading.Tasks.Task SaveSettingsAsync(Cliver.CisteraScreenCaptureService.Settings.GeneralSettings general) {
            return base.Channel.SaveSettingsAsync(general);
        }
    }
}
